version: "3.6"
services:
  prod: &base
    container_name: ${CONTAINER_NAME}
    image: node:latest
    volumes:
      - .:/source
      - /source/node_modules
      - /source/dist
    working_dir: /source
    command: bash -c "npm i && npm run build && npm start"
    ports:
      - 8080:8080
  
  dev:
    <<: *base
    container_name: ${CONTAINER_NAME}_dev
    volumes:
     - .:/source
    command: bash -c "npm i && npm run dev"
    ports:
      - 8080:${PORT}
